
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/project
    username: postgres
    password: 1234
  kafka:
    bootstrap-servers: kafka:9092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


client:
  ms-auth:
    url: "http://ms-auth:8080/"

