version: '3.9'
services:


  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - '2181'

  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.2
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - '9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes

  postgres:
    container_name: postgres
    restart: on-failure
    build:
      context: ./
      dockerfile: db/Dockerfile
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: gateway/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    image: gateway:latest
    ports:
      - '8080:8080'


  ms-auth:
    container_name: ms-auth
    build:
      context: ./
      dockerfile: ms-auth/Dockerfile
    image: ms-auth:latest
    ports:
      - '8080'
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_started

  ms-project:
    container_name: ms-project
    build:
      context: ./
      dockerfile: ms-project/Dockerfile
    image: ms-project:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080'
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started

  ms-task:
    container_name: ms-task
    build:
      context: ./
      dockerfile: ms-task/Dockerfile
    image: ms-task:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080'
    depends_on:
      postgres:
        condition: service_started

  ms-notification:
    container_name: ms-notification
    build:
      context: ./
      dockerfile: ms-notification/Dockerfile
    image: ms-notification:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080'
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started

