spring:
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

client:
  ms-project:
    url: "http://localhost:8082/"
  ms-auth:
    url: "http://localhost:8081/"
  ms-task:
    url: "http://localhost:8083/"
